languages:
  Ruby: true
  JavaScript: true
exclude_paths:
- "app/assets/javascripts/dataTables.foundation.min.js"
- "app/assets/javascripts/jquery.dataTables.min.js"
- "db/data/"
- "public/*"
- "script/*"
- "spec/*"
- "test/*"
- "vendor/*"
