source 'https://rubygems.org'
ruby '2.2.3'
gem 'acts_as_paranoid', '0.5.0.rc1'
gem 'bourbon'
gem 'carrierwave'
gem 'chartjs-ror'
gem 'coffee-rails', '~> 4.1.0'
gem 'data_migrate'
gem 'entypo-rails'
gem 'hashie'
gem 'high_voltage', '~> 3.0.0'
gem 'influxdb-rails', git: 'https://github.com/influxdata/influxdb-rails'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'mini_magick'
gem 'oj'
gem 'oj_mimic_json'
gem 'powder'
gem 'puma'
gem 'rails', '4.2.7.1'
gem "react_on_rails", "6.1.1"
gem 'sass-rails', '~> 5.0'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'administrate'
gem 'devise'
gem 'foreman'
gem 'foundation-rails', '6.2.3.0'
gem 'pg'
gem 'pundit'
gem 'sidekiq'
gem 'sinatra', :require => false
group :development do
  gem 'better_errors'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'web-console', '~> 2.0'
  gem "refills", group: :development
end
group :development, :test do
  gem 'byebug'
  gem 'factory_girl_rails'
  gem 'faker'
  # gem 'guard-rspec'
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'rspec-rails'
end
group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
  gem 'capybara-screenshot'
end
group :production do
  gem 'rails_12factor'
end
