source 'https://rubygems.org'
ruby '2.2.3'
gem 'bourbon'
gem 'coffee-rails', '~> 4.1.0'
gem 'data_migrate'
gem 'high_voltage', '~> 3.0.0'
gem 'influxdb-rails'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'oj'
gem 'oj_mimic_json'
gem 'powder'
gem 'puma'
gem 'rails', '4.2.6'
gem 'sass-rails', '~> 5.0'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'administrate'
gem 'devise'
gem 'foundation-rails', '~> 5.5'
gem 'pg'
gem 'pundit'
group :development do
  gem 'better_errors'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'web-console', '~> 2.0'
end
group :development, :test do
  gem 'byebug'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'rspec-rails'
end
group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
end
