development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: engagement-backend_development
  pool:     5
  template: template0
test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: engagement-backend_test
  pool:     5
  template: template0
production:
  adapter:  postgresql
  url:      <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  pasword:  <%= ENV['POSTGRES_PASSWORD'] %>
  encoding: unicode
  database: engagement-backend_production
  pool:     5
  template: template0
